# -*- coding: utf-8 -*-
{
    'name': "MGS Inventory Reports",
    'summary': """""",
    'description': """""",
    'author': "Meisour Solutions",
    'website': "http://www.meisour.com",
    'category': 'Reporting',
    'version': '1.0',
    'depends': ['stock', 'sale'],
    'license': 'LGPL-3',
    'data': [
        'security/ir.model.access.csv',
        'views/paperformat.xml',
        'views/report_current_stock.xml',
        'views/report_inventory_valuation_summary.xml',
        'views/report_product_moves_history.xml',
        'views/report_non_moving_items.xml',
        'views/report_reserved_items.xml',
        'wizards/current_stock.xml',
        'wizards/inventory_valuation_summary.xml',
        'wizards/product_moves_history.xml',
        'wizards/non_moving_items.xml',
        'wizards/reserved_items.xml',
    ],
} # type: ignore
